<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.cc</groupId>
        <artifactId>cc-simple-redis</artifactId>
        <version>0.0.1</version>
    </parent>

    <artifactId>redis-client</artifactId>
    <packaging>jar</packaging>

    <name>redis-client</name>
    <description>redis-client/客户端</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>

        <!-- redis-common依赖 -->
        <dependency>
            <groupId>com.cc</groupId>
            <artifactId>redis-core</artifactId>
            <version>${project.cc.version}</version>
        </dependency>
    </dependencies>
</project>
