<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.cc</groupId>
        <artifactId>zeus-kv</artifactId>
        <version>0.0.1</version>
    </parent>

    <artifactId>zeus-core</artifactId>
    <packaging>jar</packaging>
    <name>zeus-core</name>
    <description>zeus-core/核心模块</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>

        <!-- Netty依赖 -->
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.2.0.Final</version>
        </dependency>

        <!--common 依赖-->
        <dependency>
            <groupId>com.cc</groupId>
            <artifactId>zeus-common</artifactId>
            <version>0.0.1</version>
        </dependency>

    </dependencies>
</project>
